# Allow for locked-in custom names derived from colors and word list

configuration_file_version: 1

wordlist_file: words.txt
activation_length: 10
activate_any_length: true
padding: 'â'
add_serial: false
makers_mark: "Marked Item"
debug: false
namecache_invalidate_minutes: 5
namecache_max_size: 500
prevent_dblookup_spam: true
# Generally leave this false to keep the database clean
dblog_all_item_marks: false
# Leave this true to prevent wordlist changes from <maybe> breaking old renames
fail_rename_on_db_error: true
db:
  driver: mysql
  host: localhost
  name: wordbank
  port: 3306
  user: root
  password: ''
cost:
  ==: org.bukkit.inventory.ItemStack
  type: EXP_BOTTLE
  amount: 10
color:
  chars: [9, 9]
  function: com.programmerdan.minecraft.wordbank.functions.NormalDistribution
  function_terms:
  - SHA-1
word:
  max: 3
  count:
    chars: [1, 4]
    function: com.programmerdan.minecraft.wordbank.functions.Modulus
    function_terms:
    - 3 
  0:
    chars: [0, 2, 3, 9]
    function: com.programmerdan.minecraft.wordbank.functions.HashMap
    function_terms:
    - MD5
  1:
    chars: [1, 3, 4, 8]
    function: com.programmerdan.minecraft.wordbank.functions.HashMap
    function_terms:
    - MD5
  2:
    chars: [2, 5, 6, 7]
    function: com.programmerdan.minecraft.wordbank.functions.HashMap
    function_terms:
    - MD5
