name: ${project.name}
main: com.programmerdan.minecraft.wordbank.WordBank
author: ProgrammerDan
authors: []
version: ${project.version}
commands:
  wordbank:
    description: |
      Shows all utilized keys & how many times used, 
      or for a specific key how many times and by how many people they were used.
    usage: |
      /<command> [page]
      /<command> [string] [page]
    permission: wordbank.godmode

permissions:
  wordbank.*:
    description: Gives access to all wordbank features
    default: op
    children:
      wordbank.godmode: true
      wordbank.default: false
    wordbank.godmode:
      description: Allows full inspection of all possible words
      default: op
    wordbank.default:
      description: Allows players to set names using wordbank
      default: true
